import type { Metadata } from "next";
import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar";
import Main from "./components/Main";

export const metadata: Metadata = {
  title: "MY APP",
  description: "Generated by Me",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen min-w-screen">
        <div
          className="grid grid-cols-[16rem_1fr] grid-rows-[4rem_1fr_4rem] h-screen w-screen"
          style={{ minHeight: "100vh", minWidth: "100vw" }}
        >
          <div className="col-span-2 row-start-1 row-end-2">
            <Header />
          </div>
          <div className="row-start-2 row-end-3 col-start-1 col-end-2">
            <Sidebar />
          </div>
          <div className="row-start-2 row-end-3 col-start-2 col-end-3">
            <Main />
          </div>
          <div className="col-span-2 row-start-3 row-end-4">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
